# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - mkdir produccion
          - ls -la
          - mv * produccion/*
          - ls -la produccion
          - ssh migue@thegrouped.com "pwd; cd /var/www/auth/; ./execute.sh " 
    - step:
        script:
          - pipe: atlassian/slack-notify:0.3.4
            variables:
              WEBHOOK_URL: $slack_webhook_url
              MESSAGE: 'Backend nodejs desplegado correctamente'

  branches:
     '{desarrollo, test/*}':
       - step:
           script:
             - echo "No se hace nada en esta rama"